# Generated by Django 4.2.5 on 2025-09-14 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fire_detection', '0001_initial'),
    ]

    operations = [
    ]
