# Generated by Django 4.2.5 on 2025-12-27 08:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fire_detection.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fire_detection', '0002_auto_20250914_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemPerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage_percentage', models.FloatField(blank=True, null=True)),
                ('memory_usage_percentage', models.FloatField(blank=True, null=True)),
                ('active_cameras_count', models.IntegerField(default=0)),
                ('frames_per_second', models.FloatField(blank=True, null=True)),
                ('detections_per_minute', models.FloatField(default=0)),
                ('measurement_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'system_performance_metrics',
                'ordering': ['-measurement_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='camera',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='emergencycontact',
            options={'ordering': ['priority', 'category', 'name']},
        ),
        migrations.AlterModelOptions(
            name='systemconfiguration',
            options={'verbose_name': 'System Configuration', 'verbose_name_plural': 'System Configuration'},
        ),
        migrations.RemoveField(
            model_name='firedetectionevent',
            name='response_time',
        ),
        migrations.AddField(
            model_name='firedetectionevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firedetectionevent',
            name='detection_type',
            field=models.CharField(choices=[('fire', 'Fire'), ('smoke', 'Smoke'), ('heat', 'Heat')], default='fire', max_length=20),
        ),
        migrations.AddField(
            model_name='firedetectionevent',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='id',
            field=models.CharField(default=fire_detection.models.generate_uuid, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='rtsp_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='category',
            field=models.CharField(choices=[('fire_department', 'Fire Department'), ('medical', 'Medical'), ('police', 'Police'), ('security', 'Security'), ('management', 'Management')], max_length=20),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='id',
            field=models.CharField(default=fire_detection.models.generate_uuid, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='priority',
            field=models.CharField(default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='firedetectionevent',
            name='camera',
            field=models.ForeignKey(db_column='camera_id', on_delete=django.db.models.deletion.CASCADE, to='fire_detection.camera'),
        ),
        migrations.AlterField(
            model_name='firedetectionevent',
            name='confidence_score',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='firedetectionevent',
            name='id',
            field=models.CharField(default=fire_detection.models.generate_uuid, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firedetectionevent',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('false_alarm', 'False Alarm')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='camera',
            table='fire_detection_camera',
        ),
        migrations.AlterModelTable(
            name='emergencycontact',
            table='fire_detection_emergencycontact',
        ),
        migrations.AlterModelTable(
            name='firedetectionevent',
            table='fire_detection_firedetectionevent',
        ),
        migrations.AlterModelTable(
            name='systemconfiguration',
            table='fire_detection_systemconfiguration',
        ),
        migrations.CreateModel(
            name='AlertNotification',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('call', 'Call'), ('push', 'Push')], max_length=10)),
                ('recipient_contact', models.CharField(max_length=200)),
                ('message_title', models.CharField(max_length=200)),
                ('message_body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('urgency_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fire_event', models.ForeignKey(blank=True, db_column='fire_event_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='fire_detection.firedetectionevent')),
            ],
            options={
                'db_table': 'alert_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
